## Slicing Arrays

In [1]:
import numpy as np

In [2]:
a = np.arange(15)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Slicing for 1-dim arrays works exactly like python lists and tuples

In [4]:
a[5]

5

In [5]:
a[:5]

array([0, 1, 2, 3, 4])

In [6]:
a[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Slicing n-dim arrays

In [7]:
a = np.arange(36).reshape(6,6)

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [9]:
a[2,3] # Prints element in 3rd row and 4th column

15

In [10]:
a[:2,4] # Print elements in 5th column for 1st two rows

array([ 4, 10])

In [11]:
a[:2,:4] # Prints elements for 1st two rows and 1st 4 columns

array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

In [12]:
a = np.arange(36).reshape(3, 4, 3) # Creates a 3 dimensional array

In [13]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [14]:
a[:2, 1::2, :2] # Prints elements in alternating rows starting with 2nd row and first 2 columns for first 2 sub arrays

array([[[ 3,  4],
        [ 9, 10]],

       [[15, 16],
        [21, 22]]])

## Index Arrays

In [15]:
a = np.arange(11, 22)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [16]:
a[np.array([4, 4, 6, 1, 3])] # Prints an array of size 4 having values at index 4,4,6,13 in array 'a'

array([15, 15, 17, 12, 14])

In [17]:
a[np.array([[3,4,1],[8,5,1]])] # Creates a 2-dim array with values at mentioned indices from 'a'

array([[14, 15, 12],
       [19, 16, 12]])

In [18]:
a[np.array([[[8, 1], [3, 6]], [[1, 2], [3, 3]]])] # creates a 3-dim array

array([[[19, 12],
        [14, 17]],

       [[12, 13],
        [14, 14]]])

### Indexed arrays and Multi-dimensional arrays

In [19]:
a = np.arange(30).reshape(6, 5)

In [20]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [21]:
a[np.array([2,3,4])] # returns an array with 2nd,3rd,4th row of the array 'a'

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
a[np.array([2,3,4]),np.array(3)] # retruns array with elements at (2,3), (3,3) and (4,3)

array([13, 18, 23])

In [23]:
a[np.array([2,3,4]), 3] # Same as above and is preferred

array([13, 18, 23])

In [24]:
a[np.array([2, 3, 2]), np.array([3, 4, 1])] # returns elements with index values mappings (2,3), (3,4), (2,1)

array([13, 19, 11])

In [25]:
a[np.array([2,3,4]), :3] # returns array with elements from 2,3,4th row and first 3 columns

array([[10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [26]:
a[np.array([[2, 3, 2], [3, 4, 1]]), np.array([3,4,1])] #  returns 2d array with elements with index values mappings 
                                                        #   (2,3), (3,4), (2,1) and(3,3), (4,4), (1,1)

array([[13, 19, 11],
       [18, 24,  6]])

In [27]:
a[np.array([[2, 3, 4, 5], [3, 1, 3, 4], [0, 2, 4, 1]]), np.array([4, 2, 3, 2])]

array([[14, 17, 23, 27],
       [19,  7, 18, 22],
       [ 4, 12, 23,  7]])

#### Indexed Boolean arrays 

In [28]:
a = np.random.randint(11, 99, (6, 5), dtype=int)
a

array([[92, 74, 33, 73, 91],
       [84, 90, 28, 98, 15],
       [90, 95, 84, 87, 78],
       [55, 35, 55, 40, 86],
       [86, 65, 12, 52, 70],
       [13, 76, 68, 85, 74]])

In [29]:
mask = a > 50
mask

array([[ True,  True, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True]])

In [30]:
a[mask] # returns a 1d array with elements which have True in bool index array from array 'a'

array([92, 74, 73, 91, 84, 90, 98, 90, 95, 84, 87, 78, 55, 55, 86, 86, 65,
       52, 70, 76, 68, 85, 74])

In [31]:
cols = mask[:, 3] # returns values from 3rd column for every row, so this basically gives all the rows & rank of dimension 0 which is row is equal to original array
cols

array([ True,  True,  True, False,  True,  True])

In [32]:
a[cols, :] # returns rows with True in bool array from original array, in this case
             # 0th, 1st, 2nd, 4th and 5th row

array([[92, 74, 33, 73, 91],
       [84, 90, 28, 98, 15],
       [90, 95, 84, 87, 78],
       [86, 65, 12, 52, 70],
       [13, 76, 68, 85, 74]])

In [34]:
rows = mask[3, :] # returns 3rd row for every column, here we are fetching columns and so rank of dimension1 is equal to that of original array
rows

array([ True, False,  True, False,  True])

In [35]:
a[:, rows]

array([[92, 33, 91],
       [84, 28, 15],
       [90, 84, 78],
       [55, 55, 86],
       [86, 12, 70],
       [13, 68, 74]])

In [36]:
mask = (a%3 == 0)
mask

array([[False, False,  True, False, False],
       [ True,  True, False, False,  True],
       [ True, False,  True,  True,  True],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [37]:
a[mask] # since array 'a' and 'mask' have same shape so Numpy does not know what to fill at unmasked indices
# it returns a 1d array, so how do we get an array of same shape of 'a'


array([33, 84, 90, 15, 90, 84, 87, 78, 12])

In [38]:
b = np.empty_like(a, dtype='float64')
b

array([[1.e-323, 1.e-323, 0.e+000, 5.e-324, 5.e-324],
       [0.e+000, 0.e+000, 5.e-324, 1.e-323, 0.e+000],
       [0.e+000, 1.e-323, 0.e+000, 0.e+000, 0.e+000],
       [5.e-324, 1.e-323, 5.e-324, 5.e-324, 1.e-323],
       [1.e-323, 1.e-323, 0.e+000, 5.e-324, 5.e-324],
       [5.e-324, 5.e-324, 1.e-323, 5.e-324, 1.e-323]])

In [39]:
b.fill(np.nan)

In [40]:
b

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [41]:
b[mask]= a[mask] # b[mask] gives you values at indices given by mask and then we are setting those values 
# equal to values from array a

In [42]:
b

array([[nan, nan, 33., nan, nan],
       [84., 90., nan, nan, 15.],
       [90., nan, 84., 87., 78.],
       [nan, nan, nan, nan, nan],
       [nan, nan, 12., nan, nan],
       [nan, nan, nan, nan, nan]])

In [43]:
# Another way to do same thing as above using np.where
np.where(a%3==0, a , np.nan)

array([[nan, nan, 33., nan, nan],
       [84., 90., nan, nan, 15.],
       [90., nan, 84., 87., 78.],
       [nan, nan, nan, nan, nan],
       [nan, nan, 12., nan, nan],
       [nan, nan, nan, nan, nan]])

In [44]:
b = np.zeros(30).reshape(6,5)
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.where(a%3==0, a, b)

array([[ 0.,  0., 33.,  0.,  0.],
       [84., 90.,  0.,  0., 15.],
       [90.,  0., 84., 87., 78.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

## Slicing vs Indexed Arrays
#### Important Note
#### Slicing gives you VIEW of the array !! Indexing an array gives you COPY of the array

In [46]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [47]:
b = a[:3, :3]
b

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [48]:
b[1, 2] = 100
b

array([[  0,   1,   2],
       [  6,   7, 100],
       [ 12,  13,  14]])

In [49]:
a

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 100,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

#### As we can see above changing the element at (2,1) in sliced array changed its value in original array as well

In [50]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
b = a[np.array([2,3,4]), :3]
b

array([[12, 13, 14],
       [18, 19, 20],
       [24, 25, 26]])

In [52]:
b[1,1]=999
b

array([[ 12,  13,  14],
       [ 18, 999,  20],
       [ 24,  25,  26]])

In [53]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### Changing the value of (1,1) in array b, did not altered the value in original array